bind 127.0.0.1
protected-mode yes
port 6380
tcp-keepalive 300
daemonize no
supervised no
pidfile redis.pid
loglevel warning
databases 16
save 900 1
save 300 100
save 60 1
appendonly yes
dir "C:/Users/toxic/Music/bidnsteal mern/server/tools/redis/data"
